### ISSUE TITLE
Wrong markup in event_listing.pt

### ISSUE THREAD

**Issue by erral** [plone/plone.app.event#301]
When running i18ndude to extract msgids, i18ndude complains with the following error in event_listing.pt:

```
('There was an error processing', 'plone.app.event/plone/app/event/browser/event_listing.pt')
Traceback (most recent call last):
  File "/home/erral/downloads/eggs/i18ndude-5.3.0-py2.7.egg/i18ndude/extract.py", line 543, in tal_strings
    parser.parseFile(filename)
  File "/home/erral/downloads/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 166, in parseFile
    self.parseString(data)
  File "/home/erral/downloads/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 173, in parseString
    self.feed(data)
  File "/usr/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/lib/python2.7/HTMLParser.py", line 161, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python2.7/HTMLParser.py", line 327, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "/home/erral/downloads/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 188, in handle_starttag
    self.close_para_tags(tag)
  File "/home/erral/downloads/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 257, in close_para_tags
    raise OpenTagError(self.tagstack, tag, self.getpos())
OpenTagError: Tag <ul> is not allowed in <nav>, at line 14, column 7

```

We may want to change that markup, but it may have some styling implications. 

See the original file here: https://github.com/plone/plone.app.event/blob/master/plone/app/event/browser/event_listing.pt#L13

**Comment by erral** [comment]
Here is the relevant less file: 

https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/event.plone.less#L23

We need to change this also if we change de markup.

**Comment by jensens** [comment]
Closing as outdated. Wrong markup breaking i18ndude on Python 2.7. Templates rewritten.
If you think this issue is still relevant please reopen it. Thank you for the original report!
