### ISSUE TITLE
Recursion error because upgraded events portlets missing attribute

### ISSUE THREAD

**Issue by rpatterson** [plone/plone.app.event#305]
Some attributes were added to the events portlet assignment class.  Portlets added before this result in the following recursion error when the code is upgraded:

```
2019-04-29 18:10:09 ERROR imageportlet Error while determining renderer availability of portlet ('context' '/...' 'events'): maximum recursion depth exceeded
Traceback (most recent call last):
  File "eggs/plone.portlets-2.3-py2.7.egg/plone/portlets/manager.py", line 117, in _lazyLoadPortlets
    isAvailable = renderer.available
  File "src/plone.app.event/plone/app/event/portlets/portlet_events.py", line 141, in available
    return self.data.count > 0 and len(self.events)
  File "src/plone.app.event/plone/app/event/portlets/portlet_events.py", line 154, in events
    if ICollection and ICollection.providedBy(self.search_base):
  File "src/plone.app.event/plone/app/event/portlets/portlet_events.py", line 122, in search_base
    if not self._search_base and self.data.search_base_uid:
  File "src/plone.app.event/plone/app/event/portlets/portlet_events.py", line 106, in _uid
    path = self.search_base
...
  File "src/plone.app.event/plone/app/event/portlets/portlet_events.py", line 122, in search_base
    if not self._search_base and self.data.search_base_uid:
  File "src/plone.app.event/plone/app/event/portlets/portlet_events.py", line 106, in _uid
    path = self.search_base
RuntimeError: maximum recursion depth exceeded
```

We should add an upgrade step that fixes this on existing assignments.

**Comment by jensens** [comment]
Closing as outdated. Recursion error in events portlet on Plone 4 era upgrade path.
If you think this issue is still relevant please reopen it. Thank you for the original report!
